apiVersion: v1
kind: Service
metadata:
    name: php-fpm
    labels:
        app: php-fpm
spec:
    ports:
    - port: 6000
    selector:
        app: php-fpm
        tier: backend
    type: LoadBalancer