apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: sw-pv-claim
    labels:
        app: shopware
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi